# Header

menu:
  主页: /
  日记: /tags/日记/

# SubNav
subnav:
  github: "https://github.com/zhengjf9/"
  weibo: "https://weibo.com/2951463210/profile?topnav=1&wvr=6"
  zhihu: "https://www.zhihu.com/people/zheng-jia-feng-87/activities"
  qq: "http://wpa.qq.com/msgrd?v=3&uin=1773643139&site=qq&menu=yes"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #mail: "mailto:litten225@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: true
# 是否在新窗口打开链接
open_in_new: false
fancybox: true

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '您的支持，是我不断努力的动力！'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /assets/img/alipay.png
# 微信二维码图片地址
weixin: /assets/img/weixin.png

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '本文章未设置目录'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: 'a30844fa2bcbce0a9e001fe06cefeddf'
google_analytics: false
favicon: /assets/img/favicon.ico

#你的头像url
avatar: /assets/img/photo.jpeg

#是否开启分享
share_jia: true

mobile:
  social: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: true

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: 'cytlS3BTr'
changyan_conf: '2f3f8d69b657fa191106a99cb22cdf49'

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  我的CSDN博客: http://blog.csdn.net/zhengjf9/

aboutme: 中山大学软件工程，15级 ，热爱生活，热爱编程，折腾过C，C++，Java，Web，Android，Python，cocos2d-x，Unity3D， UWP，数据库，算法……
         建立这个博客，有三方面的原因：首先，是为了给自己提供一个思考和总结的机会，避免浑浑噩噩地埋头苦干；其次，用过国内的许多技术博客，
         体验都不是很好，所以当听说有hexo + github pages这种方式可以简便地DIY自己的博客时，就毫不犹豫地做了一个；最后，如果可能的话，也希望
         能够通过这个博客与兴趣相同的朋友一起讨论、学习，共同进步！
post_asset_folder: true